email_domain_restriction_domains: 'example.com'
email_domain_restriction_message: 'Email domain not valid.'
email_domain_restriction_behaviour: 0
email_domain_restriction_apply_current_fields: 0
email_domain_restriction_message_to_change: 'Your email is not valid anymore. Please, change it as soon as possible.'
